calcPowerSpec;
powerRS(:,:,tt)=latePowerRS;
powerIB(:,:,tt)=latePowerIB;
% meanDuringPowerRSall(:,tt)=meanDuringPowerRS;
% meanDuringPowerIBall(:,tt)=meanDuringPowerIB;
% devDuringPowerRSall(:,tt)=devDuringPowerRS;
% devDuringPowerIBall(:,tt)=devDuringPowerIB;
meanLatePowerRSall(:,tt)=meanLatePowerRS;
meanLatePowerIBall(:,tt)=meanLatePowerIB;
devLatePowerRSall(:,tt)=devLatePowerRS;
devLatePowerIBall(:,tt)=devLatePowerIB;