function newS=synapse(oldS,tauRise,tauDecay,Vpre,dt)
newS=oldS+dt*( ...
    -oldS./tauDecay ...
    +(1-oldS)./tauRise.*(1+tanh(Vpre/10))/2 ...
    );

% Used the following (not dividing by 2) till Nov '17. But then adjusted
% all rise time constants.

% newS=oldS+dt*( ...
%     -oldS./tauDecay ...
%     +(1-oldS)./tauRise.*(1+tanh(Vpre/10)) ...
%     );